version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz2wsx!@QW
      MYSQL_DATABASE: auth_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6380:6379"

  station-discovery-service:
    build: ./station-discovery-service
    container_name: station-discovery-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - redis
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=dev  # This tells Spring Boot to use the 'dev' @Profile!
      - GOOGLE_MAPS_API_KEY=AIzaSyBXt15eZKc_elG7OWqgimsnkIIb2z3nB1g  # This passes the key to the container
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/station_db
      - SPRING_REDIS_HOST=redis
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092

  frontend:
    build: ../frontend/ev-charge-web
    container_name: frontend
    ports:
      - "3000:80"


volumes:
  mysql_data:
