server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/auth_db?createDatabaseIfNotExist=true
    username: root
    password: ${MYSQL_PASSWORD:1qaz2wsx!@QW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:10090}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
